### ISSUE TITLE
projection option not effective for worldMap

### ISSUE THREAD

**Issue by mmrj** [forio/contour-geo#28]
because world-map.js:16: " projection: (d3.geo.miller || d3.geo.equirectangular)(),", there is no ability for your config option to override

when we fix this, we need to test USMap, worldMap, and map. (i was anecdotally having some weird problems with USMap and i think this just needs regression testing)

**Comment by jaimedp** [comment]
Looking at the code I think we can override the projection but the problem with that example is that is missing a closing bracket and paren `})`  after the render, than the feature should be `all`, so this should work:

```
$(function () {
    d3.json('http://forio.com/tools/contour/geo/maps/world.json', function(mapUnit) {
        new Contour({
            el: '.myMap'
        })
        .geo()
        .map(mapUnit, {
        	projection: d3.geo.azimuthalEqualArea(),
        	feature: 'all',
        	scale: 100
        })
        .render();
    })
});
```

**Comment by mmrj** [comment]
verified, that was the problem. derp. sorry about that!
